name: PhilTimeline
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pandas
  - scipy
  - fastapi
  - sqlalchemy
  - sparqlwrapper
  - alembic
  - psycopg2
  - pip
  - pip:
    - uvicorn
    - pytest
